export const NAMES_EN_CONST = {
  vowels: 'aeiou',
  consonants: 'bcdfghklmnprstw',
  endings: [
    ['a', 'ana', 'e', 'en', 'er', 'ia', 'ie', 'ina', 'ine', 'y', 'yn'],
    [
      'ald',
      'an',
      'ard',
      'art',
      'arth',
      'arts',
      'e',
      'ech',
      'eck',
      'eld',
      'ell',
      'en',
      'er',
      'erd',
      'ert',
      'erts',
      'es',
      'ich',
      'ick',
      'ill',
      'in',
      'ith',
      'low',
      'man',
      'n',
      'och',
      'ock',
      'old',
      'oll',
      'or',
      'ord',
      'ort',
      'orth',
      'orts',
      's',
      'son',
      'ton',
      'uch',
      'uck',
      'y',
    ],
  ],
};
