/**
 * Creates an array of a specified length, filled with values generated by a callback function.
 * @param {any} n - The length of the new array.
 * @param {Function} [callback=(i: any) => i] - A function that generates the value for each element in the array. Defaults to identity function.
 * @returns {Array<any>} - The new array filled with generated values.
 */
export function randomArray(n: any, callback = (i: any) => i): Array<any> {
  return [...Array(n)].map((_, i) => callback(i));
}
